## konlpy로 synop 명사 추출
## CountVectorizer, cosine_similarity

In [1]:
import pandas as pd
import numpy as np
from konlpy.tag import *

In [2]:
metadata = pd.read_csv('data_nountag_ebs.csv', encoding='cp949')

In [3]:
metadata.head()

idx   tv  title                               epi       dates  \
0    0  EBS  다큐프라임        비밀의 땅 파미르   2부 비밀의 땅 숨겨진 강  2018.09.11   
1    1  EBS  다큐프라임              비밀의 땅 파미르  1부 세계의 지붕  2018.09.10   
2    2  EBS  다큐프라임  위대한 로마 제작노트  로마는 하루아침에 이루어지지 않았다  2018.09.05   
3    3  EBS  다큐프라임                       제국의 도시  폼페이  2018.09.04   
4    4  EBS  다큐프라임                   황제들의 정치무대  콜로세움  2018.09.03   

                                               links  \
0  http://www.ebs.co.kr/tv/showcourseId=BP0PAPB00...   
1  http://www.ebs.co.kr/tv/showcourseId=BP0PAPB00...   
2  http://www.ebs.co.kr/tv/showcourseId=BP0PAPB00...   
3  http://www.ebs.co.kr/tv/showcourseId=BP0PAPB00...   
4  http://www.ebs.co.kr/tv/showcourseId=BP0PAPB00...   

                                               synop  \
0  아시아의 고산지대인 파미르 텐샨히말라야 의 자연과 사람들의 삶을 알아본다. 중앙아시...   
1  세계의 지붕 파미르에 서식하는 다양한 야생동물들의 생태소개 1부에서는 파미르에 서식...   
2   위대한 로마의 촬영 기간은 총 6주로 3주간 튀니지에서 재연 촬영을 했고 나머지 ...   
3  폼페이를 첨단 그래픽과 3D 입체영상으로 완벽 복원한다.  콜로세움이 완성되어 가던...   
4       로마 최대 원형경기장 콜로세움을 첨단 그래픽과 3D 입체영상으로 완벽 복원한다.   

                                                 tag  
0  파미르 텐샨 히말라야 사람들 아랄해 아무다리아강 시르다리아강 주요 빙하 타지키스탄 ...  
1  서식 세계 지붕 파미르 야생 야생동물 지역 포식자 늑대 중심 눈표범 마르코폴 동물 ...  
2                     로마 6주 폼페이 사건 최대 제국 역사 시간 황제 우리  
3                                                폼페이  
4                                                NaN

# Synop에서 명사 추출 konlpy Hannanum

In [4]:
han = Hannanum()

# 메타데이터의 synop을 synoplist에 넣은 후 명사 추출
synoplist = metadata['synop']
synoplist.head()

0    아시아의 고산지대인 파미르 텐샨히말라야 의 자연과 사람들의 삶을 알아본다. 중앙아시...
1    세계의 지붕 파미르에 서식하는 다양한 야생동물들의 생태소개 1부에서는 파미르에 서식...
2     위대한 로마의 촬영 기간은 총 6주로 3주간 튀니지에서 재연 촬영을 했고 나머지 ...
3    폼페이를 첨단 그래픽과 3D 입체영상으로 완벽 복원한다.  콜로세움이 완성되어 가던...
4         로마 최대 원형경기장 콜로세움을 첨단 그래픽과 3D 입체영상으로 완벽 복원한다.
Name: synop, dtype: object

In [5]:
# 불용어 제거 안함.
han.nouns(synoplist[0])

# 에피소드 제목의 명사를 계산에 사용?
#불용어 제거 안함
#epilist = metadata['epi']
#epilist.head()

['아시아',
 '고산지대',
 '파미르',
 '텐샨히말라야',
 '의',
 '자연',
 '사람',
 '삶',
 '중앙아시아',
 '거대',
 '호수',
 '아랄해',
 '지금',
 '20세',
 '최악',
 '환경재앙',
 '곳',
 '2부',
 '아랄해',
 '두',
 '물줄기',
 '아무다리아강',
 '시르다리아강',
 '발원지',
 '여정',
 '주요',
 '에피소드',
 '아무다리아강',
 '발원지',
 '파미르고원',
 '대륙빙하',
 '중',
 '최대',
 '규모',
 '파미르의',
 '페드첸코',
 '빙하',
 '판즈강',
 '아무다리아',
 '강',
 '타지키스탄',
 '아프가니스탄',
 '국경',
 '강',
 '판즈강',
 '수',
 '아프가니스탄',
 '사람',
 '모습',
 '수',
 '빙하',
 '습지대',
 '식생',
 '변화',
 '환경',
 '변화',
 '강',
 '사람',
 '삶',
 '소개',
 '시르다리아강',
 '발원지',
 '텐샨산맥',
 '파미르',
 '고원',
 '고도',
 '텐샨산맥',
 '풍경',
 '자랑',
 '초록',
 '산',
 '색색',
 '꽃',
 '화',
 '텐샨',
 '시르다리야강',
 '발원지',
 '텐샨',
 '빙하',
 '모습',
 '소개',
 '자일로여름',
 '초목지',
 '유르트',
 '양',
 '키르',
 '유목민',
 '텐샨산맥',
 '야생동물',
 '한',
 '번',
 '공개',
 '적',
 '비밀',
 '땅',
 '세계',
 '지붕',
 '파미르',
 '거대산맥들',
 '해발',
 '4000m',
 '고지세계',
 '최초',
 '하나',
 '먹이',
 '벌',
 '최상위',
 '포식자',
 '신경전총',
 '제작기간',
 '2년',
 '추적',
 '잠복',
 '제작진',
 '집요함',
 '대작',
 '파미르고원',
 '번',
 '적',
 '익숙',
 '이름',
 '국내',
 '소개',
 '적',
 '비밀',
 '땅',
 '파미르고원',
 '히말라야산맥',
 '비롯',
 '텐샨',
 '카

In [6]:
# 명사추출 확인
han.nouns(synoplist[0])

['아시아',
 '고산지대',
 '파미르',
 '텐샨히말라야',
 '의',
 '자연',
 '사람',
 '삶',
 '중앙아시아',
 '거대',
 '호수',
 '아랄해',
 '지금',
 '20세',
 '최악',
 '환경재앙',
 '곳',
 '2부',
 '아랄해',
 '두',
 '물줄기',
 '아무다리아강',
 '시르다리아강',
 '발원지',
 '여정',
 '주요',
 '에피소드',
 '아무다리아강',
 '발원지',
 '파미르고원',
 '대륙빙하',
 '중',
 '최대',
 '규모',
 '파미르의',
 '페드첸코',
 '빙하',
 '판즈강',
 '아무다리아',
 '강',
 '타지키스탄',
 '아프가니스탄',
 '국경',
 '강',
 '판즈강',
 '수',
 '아프가니스탄',
 '사람',
 '모습',
 '수',
 '빙하',
 '습지대',
 '식생',
 '변화',
 '환경',
 '변화',
 '강',
 '사람',
 '삶',
 '소개',
 '시르다리아강',
 '발원지',
 '텐샨산맥',
 '파미르',
 '고원',
 '고도',
 '텐샨산맥',
 '풍경',
 '자랑',
 '초록',
 '산',
 '색색',
 '꽃',
 '화',
 '텐샨',
 '시르다리야강',
 '발원지',
 '텐샨',
 '빙하',
 '모습',
 '소개',
 '자일로여름',
 '초목지',
 '유르트',
 '양',
 '키르',
 '유목민',
 '텐샨산맥',
 '야생동물',
 '한',
 '번',
 '공개',
 '적',
 '비밀',
 '땅',
 '세계',
 '지붕',
 '파미르',
 '거대산맥들',
 '해발',
 '4000m',
 '고지세계',
 '최초',
 '하나',
 '먹이',
 '벌',
 '최상위',
 '포식자',
 '신경전총',
 '제작기간',
 '2년',
 '추적',
 '잠복',
 '제작진',
 '집요함',
 '대작',
 '파미르고원',
 '번',
 '적',
 '익숙',
 '이름',
 '국내',
 '소개',
 '적',
 '비밀',
 '땅',
 '파미르고원',
 '히말라야산맥',
 '비롯',
 '텐샨',
 '카

In [7]:
# s_nounlist 만들어서 명사문자 시놉시스 넣기

s_nounslist = []

for synop in synoplist:
    s_nouns = ' '.join(han.nouns(synop))
    #print(s_nouns)
    s_nounslist.append(s_nouns)

In [8]:
# s_nounlist 확인
s_nounslist[0]

'아시아 고산지대 파미르 텐샨히말라야 의 자연 사람 삶 중앙아시아 거대 호수 아랄해 지금 20세 최악 환경재앙 곳 2부 아랄해 두 물줄기 아무다리아강 시르다리아강 발원지 여정 주요 에피소드 아무다리아강 발원지 파미르고원 대륙빙하 중 최대 규모 파미르의 페드첸코 빙하 판즈강 아무다리아 강 타지키스탄 아프가니스탄 국경 강 판즈강 수 아프가니스탄 사람 모습 수 빙하 습지대 식생 변화 환경 변화 강 사람 삶 소개 시르다리아강 발원지 텐샨산맥 파미르 고원 고도 텐샨산맥 풍경 자랑 초록 산 색색 꽃 화 텐샨 시르다리야강 발원지 텐샨 빙하 모습 소개 자일로여름 초목지 유르트 양 키르 유목민 텐샨산맥 야생동물 한 번 공개 적 비밀 땅 세계 지붕 파미르 거대산맥들 해발 4000m 고지세계 최초 하나 먹이 벌 최상위 포식자 신경전총 제작기간 2년 추적 잠복 제작진 집요함 대작 파미르고원 번 적 익숙 이름 국내 소개 적 비밀 땅 파미르고원 히말라야산맥 비롯 텐샨 카라코람 쿤룬 힌두쿠시 산맥 곳 평균 해발고도 4000m 산악 들 히말라야 누구 손길 미지 땅 삭막 땅 발 생명들 소개 자연다큐멘터리 명 답 수 야생동물들 모습 무 카메라 설치 촬영 영상 늑대무리 위계질서 먹이 포식자 면모 수 눈표범 늑대 장면 녀석들 제작진 집요함 지 반증 진귀 영상 사냥 마르코폴로양 눈표범 대가 전리품 늑대 둘 신경전 포착 촬영 외 아이벡스야생 염소 마르코폴로산양 수염 수리 등 파미르 서식 다양한 야생동물 생태 밀 다큐 본방송 2014 06 1618 밤 9시 50분재방송 2014 06 22 밤 8시 15분 3부작 연속 방영제작진제작진 기획 추덕담연출 서준기획의도세계 지붕 파미르 고원 한번쯤 적 익숙 이름 국내 소개 바 파미르 텐샨 카라코람 산맥 쿤룬 산맥 등 험준 고산들 지점 형성 고원지대 그 세계 지붕 히말라야 매력 지역 파미르 고원 위치해 타지키스탄 아프가니스탄 파키스탄 키르기스스탄 중국 등 나라들 국경 불안 정세 접근 허락 곳 산악인 도전 히말라야 파미르 누구 손길 미지 땅 곳 평균 해발 4000

# TfidfVectorizer

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.pipeline import make_pipeline

In [ ]:
pipe = make_pipeline(TfidfVectorizer(min_df=5), 

In [10]:
# tfidf 행렬 만들기 
# 선형변환, 벡터-행렬

tfidf = TfidfVectorizer(min_df=1)
tfidf_matrix = tfidf.fit_transform(s_nounslist)

synop_distance = (tfidf_matrix * tfidf_matrix.T)

In [11]:
print('유사도 분석 행렬 ' + str(synop_distance.get_shape()[0]) + 'x' + str(synop_distance.get_shape()[1]) + ' matrix.')
print(synop_distance.toarray())

유사도 분석 행렬 926x926 matrix.
[[1.         0.62159165 0.02143245 ... 0.06314138 0.06821796 0.03217229]
 [0.62159165 1.         0.01730035 ... 0.12037887 0.06734516 0.02710061]
 [0.02143245 0.01730035 1.         ... 0.00947542 0.         0.01992976]
 ...
 [0.06314138 0.12037887 0.00947542 ... 1.         0.         0.45311651]
 [0.06821796 0.06734516 0.         ... 0.         1.         0.        ]
 [0.03217229 0.02710061 0.01992976 ... 0.45311651 0.         1.        ]]


In [23]:
cosine_similarity(tfidf_matrix[0:1], tfidf_matrix)

array([[1.00000000e+00, 6.21591646e-01, 2.14324471e-02, 1.93662766e-03,
        1.07326523e-02, 1.85107796e-02, 1.07387356e-02, 3.45624606e-03,
        2.15174858e-02, 2.83752587e-02, 3.24198591e-02, 5.49596279e-02,
        3.93222541e-02, 5.09503846e-02, 3.03595498e-02, 3.11403416e-02,
        3.21777113e-02, 2.95702124e-02, 1.27026857e-02, 1.80396092e-02,
        2.96107410e-02, 2.17263502e-02, 1.24654681e-02, 1.91367350e-02,
        1.48303168e-02, 1.77583064e-02, 1.85241832e-02, 2.51878079e-02,
        3.08943896e-02, 2.61880592e-02, 2.04844498e-02, 1.75611330e-02,
        1.75335537e-02, 1.17480760e-02, 1.04829161e-02, 1.55102982e-02,
        1.91607353e-02, 1.23286299e-02, 2.79411451e-02, 7.77855267e-03,
        8.52366338e-03, 2.39867971e-02, 4.03314088e-03, 9.47285757e-03,
        1.92007001e-02, 2.44477769e-02, 2.82303393e-02, 3.26177764e-02,
        1.55170774e-02, 1.38290253e-02, 7.84670243e-03, 1.05609457e-02,
        8.52777879e-03, 5.43805553e-03, 3.75631286e-02, 1.460399

# xxxxx

In [ ]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix_train = tfidf_vectorizer.fit_transform(train_set)  #finds the tfidf score with normalization
print "cosine scores ==> ",cosine_similarity(tfidf_matrix_train[0:1], tfidf_matrix_train)  #here the first element of tfidf_matrix_train is matched with other three elements

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim2 = cosine_similarity(count_matrix, count_matrix)



# index는 dataframe의 idx
indices = pd.Series(metadata.index, index=metadata['idx'])




def get_recommendations(idx, cosine_sim2=cosine_sim2):
    #제목과 일치하는 에피소드 인덱스 가지고옴
    idx = indices[idx]
    
    sim_scores = list(enumerate(cosine_sim2[idx]))
    
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    #비슷한 에피소드 상위 10개
    sim_scores = sim_scores[1:11]
    
    # indices
    epi_indices = [i[0] for i in sim_scores]
    
        
    return metadata['epi'].iloc[epi_indices]




print('episode : '+ metadata['epi'][400])
get_recommendations(400, cosine_sim2)